# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
r: bioc-devel

r_build_args: --keep-empty-dirs --no-resave-data
r_check_args: --no-vignettes --timings --no-examples

matrix:
  include:
    - os: osx
    - os: linux

after_success:
  - Rscript -e 'lintr::lint_package(".")'
  - Rscript -e 'BiocCheck::BiocCheck(".")'
