# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
r: bioc-devel
matrix:
  include:
    - os: linux
    - os: osx

after_success:
  - Rscript -e 'BiocCheck::BiocCheck(".")'
  - Rscript -e 'devtoo::push_readme_md("vignettes/HMP16SData.Rmd")'
